#GENERATE_RC_FROM_DOC# cf unbind-service SERVICE_TO_FACADE_APP_NAME GATEWAY_NAME && cf bind-service SERVICE_TO_FACADE_APP_NAME GATEWAY_NAME -c route.json
#NO_GENERATE_RC_FROM_DOC# cf unbind-service SERVICE_TO_FACADE_APP_NAME GATEWAY_NAME && cf bind-service SERVICE_TO_FACADE_APP_NAME GATEWAY_NAME -c route.json
