#@ load("@ytt:data","data")
---
service:
  filters: #@ data.values.serviceFilters
  #@ if data.values.servicePredicatePath != "":
  pathPrefix: #@ data.values.servicePredicatePath
  #@ end
  #@ if data.values.specifyPredicateHost: 
  predicates: 
  - #@ "Host=" + data.values.servicePredicateHost
  #@ end
openapi:
  location: #@ data.values.serviceOpenApiUrl
#@ if data.values.routeConfigurationOverridesEnabled:
routes: #@ data.values.routesArray
#@ end