#@ load("@ytt:data","data")
---
service:
  filters: #@ data.values.serviceFilters
  #@ if data.values.servicePredicatePath != "":
  path-prefix: #@ data.values.servicePredicatePath
  #@ end
  #@ if data.values.specifyServicePredicates: 
  predicates: #@ data.values.servicePredicates
  #@ end
openapi:
  location: #@ data.values.serviceOpenApiUrl
#@ if data.values.routeConfigurationOverridesEnabled:
routes: #@ data.values.routesArray
#@ end