#@ load("@ytt:overlay","overlay")

#@overlay/match by=overlay.all
---
routes:
  - order: 10
    method: OPTIONS
    path: /api/customer-profiles/**
    filters:
    - StripPrefix=0
    model: {}



  #@overlay/match by=overlay.all, expects="1+"
  - 
    #@overlay/match missing_ok=True
    metadata:
      cors:
        allowedOrigins: 
        - "*"
        allowedMethods:
        - GET
        - PUT
        - POST
        - DELETE
        - OPTIONS
        allowedHeaders: 
        - "*"
        allow-credentials: true
    filters:
    - "DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST"
  